# get version from setup.py
{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: autophot
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python

requirements:
  build:
    - python>=3.6
    - setuptools
  run:
    {% for req in data.get('install_requires', []) %}
      - {{ req }}
    {% endfor %}

test:
 imports:
   - autophot

about:
  home: https://github.com/Astro-Sean/autophot
  license: GPL-3.0
  license_file: license
  description: The AUTOmated Photometry Of Transients (AutoPhOT) is a novel automated pipeline that is designed for rapid, publication-quality photometry of transients.
  summary: AUTOmated Photometry Of Transients (AutoPhOT) photometric pipeline
