# get version from setup.py
{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: autophot
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python

requirements:
  build:
    - python>=3.6
    - setuptools
  run:
    {% for req in data.get('install_requires', []) %}
      - {{ req }}
    {% endfor %}

test:
 imports:
   - autophot

about:
  home: https://github.com/Astro-Sean/autophot
  license: ccbysa-4.0
  license_file: license
  description: Automated Photometry of Transients Photometric Pipeline
  summary: Preparing initial upload
